### ISSUE TITLE
sound delay

### ISSUE THREAD

**Issue by corint1** [chris1111/VoodooHDA-macOS-High-Sierra#1]
hello 
why when us this kext on hdmi soun have delay ? aprox 1 sec. if use this kext need other apps flowersound. with this apps delay disappear . flowersound isn't compatible with highsierra and need other apps to correct this ...and etc etc etc ...
is it possible to make sound without delay ?
use on gtx 1050 ti 
thank you

**Comment by chris1111** [comment]
Post your question to the Developer because I do not have the answer
Download the Latest Release [VoodooHDA 290 ➤ Forum VoodooHDA 290](http://www.insanelymac.com/forum/topic/314406-voodoohda-290/page-15)

**Comment by corint1** [comment]
thank you ...
